Update to v1.1.0
AnacondaRecipes/anaconda_prompt-feedstock pull request #3
Opened 2024-08-29 19:40 UTC by marcoesters

{package} {version} {:snowflake:}

**Destination channel:** {Snowflake | defaults}

### Links

- [{ticket_number}]() 
- [Upstream repository]()
- [Upstream changelog/diff]()
- Relevant dependency PRs:
  - ...

### Explanation of changes:

- ...

2024-09-04 13:25 UTC, pseudoyim requested changes

2024-09-04 13:25 UTC, pseudoyim commented on recipe/LICENSE
> +The content of this package usess the BSD-3-Clause license (see LICENSE-BSD-3-Clause) EXCEPT for files ending in .ico, .icns, and .png. These files fall under Create Commons Attribution Non Commercia
```suggestion
The content of this package uses the BSD-3-Clause license (see LICENSE-BSD-3-Clause) EXCEPT for files ending in .ico, .icns, and .png. These files fall under Create Commons Attribution Non Commercial No Derivatives 4.0 International license (see LICENSE-CC-BY-NC-ND-4.0).
```

2024-09-04 13:56 UTC, pseudoyim approved these changes

2024-09-18 07:05 UTC, skupr-anaconda approved these changes
LGTM but `menuinst` in `run_constrained` should be aligned with the version in `post-link.bat`

2024-09-18 07:05 UTC, skupr-anaconda commented on recipe/post-link.bat
> +%PYTHON_CMD% -c "import menuinst, sys; sys.exit(1 if tuple(int(x) for x in menuinst.__version__.split('.'))[:3] < (2, 1, 1) else 0)"
There is `menuinst >=2.1.0` in `run_constrained`. Should it be there `menuinst >=2.1.1`?

2024-09-24 16:57 UTC, merged